services:
  app:
    image: node:latest
    container_name: exchange_app
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    command: sh -c "npm install && npm run start"
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    env_file:
      - .env
